In [6]:
# import packages
from fractions import Fraction
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import math
import cvxpy as cvx
import math
import random
# from collections import deque

In [9]:
def all_connections(s):
    """returns all valid connections in MISS

    Args:
        s (list): sequence to generate connections from

    Returns:
        list of tuples: (x1, x2) where (x1, s[x1]) (x2, s[x2]) is a valid connection of up and right paths that are part of a MISS
    """
    # adding auxilary source and sinka
    s = s.copy()
    s.insert(0, 0)
    s.append(len(s))

    connections = []
    for i in range(len(s)):
        for j in range(i, len(s)):
            # using the above rule
            if ((j - i) * (s[j] - s[i])) > 0:
                connections.append((i, j))
    # gets rid of duplicates
    connections = list(set(connections))

    # plt.figure(figsize=(6, 6))
    # plt.scatter(range(0, len(s)), s)

    valid_connections = set()

    for connection in connections:
        if not in_box(connection, s):
            valid_connections.add((connection[0] + 1, connection[1] + 1))
            x1, x2 = connection[0], connection[1]
            # plt.plot([x1, x2], [s[x1], s[x2]], color='tan')

    # plt.xticks(range(0, len(s) + 1))
    # plt.yticks(range(0, len(s) + 1))
    # plt.grid(True)

    connections = sorted(list(valid_connections))

    return connections


def in_box(t, s):
    """returns whether there is another point in the box extending horizontal and vertical lines from both points

    Args:
        t (tuple): connection to be checked
        s (list): main seequence

    Returns:
        bool: whether there exists a point in the box
    """
    i, j = t[0], t[1]
    if any(s[x] < s[j] and s[x] > s[i] for x in range(i + 1, j)):
        return True
    return False

def find_sources(s):
    """finds sources of a sequence (all sources of MISS)

    Args:
        s (list): main sequence

    Returns:
        list: indices of source nodes
    """
    return [i for i, element in enumerate(s) if all(element < x for x in s[:i])]

def recursive_method(s):
    """calls recursive function to find all MISS

    Args:
        s (list): main sequence

    Returns:
        2D numpy array: usage matrix MISS
    """
    m = np.empty((0, len(s)))
    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if len(greater) == 0:
            nonlocal m
            m = np.concatenate((m, [row]), axis=0)
            return
        for element in greater:
            recurse(s, element, row.copy())

    for source in find_sources(s):
        recurse(s, source, np.zeros(len(s))) 
    return m

def MISS_from_connections(c, s_len):
    """uses networkx to find the usage matrix of MISS from a list of possible valid connections

    Args:
        c (list of tuples): connections

    Returns:
        2D numpy array: usage matrix
    """
    g = nx.DiGraph()
    g.add_edges_from(c)
    
    m = np.empty((0, s_len))
        
    sink_nodes = [node for node, out_degree in g.out_degree() if out_degree == 0]
    source_nodes = [node for node, in_degree in g.in_degree() if in_degree == 0]
    for (source, sink) in [(source, sink) for sink in sink_nodes for source in source_nodes]:
        for path in nx.all_simple_paths(g, source=source, target=sink):
            row = np.zeros(s_len)
            for i in path:
                # shifting since auxiliary source and sink should not be in usage matrix
                if i != 1 and i != s_len+2:
                    row[i - 2] = 1
            m = np.concatenate((m, [row]), axis=0)

    return m

def networkx_method(pi):
    return MISS_from_connections(all_connections(pi), len(pi))

def improved_recursive(s):
    m_rows = []

    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))
        
    return np.array(m_rows)

# pi = [7, 3, 1, 17, 10, 18, 9, 20, 6, 12, 16, 13, 2, 8, 19, 4, 15, 11, 14, 5]
# pi = [2, 4, 9, 3, 5, 7, 6, 8, 1]
pi = [2, 1, 3]

print("pi: ", pi)

print("usage matrix using recursive function:")
r = recursive_method(pi)
r = r[np.lexsort(r.T)]
print(r)
print("usage matrix using networkx method:")
n = networkx_method(pi)
n = n[np.lexsort(n.T)]
print(n)
print("usage matrix using improved recursive function:")
i = improved_recursive(pi)
i = i[np.lexsort(i.T)]
print(i)

# plt.figure(figsize=(6, 6))
# plt.scatter(range(1, len(pi) + 1), pi)
# for row in n:
#     indices = np.nonzero(row)
#     plt.plot(indices[0] + 1, [pi[i] for i in indices[0]], color='tan')
# plt.xticks(range(0, len(pi) + 2))
# plt.yticks(range(0, len(pi) + 2))
# plt.grid(True)

print(f"Outputs of all methods are equal: {np.array_equal(n, r) and np.array_equal(n, i)}")

pi2 = [2, 3,1]
i2 = improved_recursive(pi2)
i2 = i2[np.lexsort(i2.T)]
print(i2)

pi:  [2, 1, 3]
usage matrix using recursive function:
[[1. 0. 1.]
 [0. 1. 1.]]
usage matrix using networkx method:
[[1. 0. 1.]
 [0. 1. 1.]]
usage matrix using improved recursive function:
[[1. 0. 1.]
 [0. 1. 1.]]
Outputs of all methods are equal: True
[[1. 1. 0.]
 [0. 0. 1.]]


In [13]:
def find_sources(s):
    return [i for i, element in enumerate(s) if all(element < x for x in s[:i])]

def generate_N(s):
    m_rows = []

    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))
        
    return np.array(m_rows)

def shortest_path(s, w):
    m = np.empty((0, len(s)))
    lightest = np.empty(len(s))
    lightest_value = math.inf
    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if len(greater) == 0:
            nonlocal m, lightest, lightest_value
            m = np.concatenate((m, [row]), axis=0)
            value = np.dot(row, w)
            if value < lightest_value:
                lightest_value = value
                lightest = row
            return
        for element in greater:
            recurse(s, element, row.copy())

    for source in find_sources(s):
        recurse(s, source, np.zeros(len(s))) 

    return m, lightest, lightest_value

# this doens't return N but does give the correct value for modulus
def fast_shortest_path(s, w):
    m_rows = []
    lightest = []
    lightest_value = math.inf

    def recurse(s, x, row):
        nonlocal m_rows, lightest, lightest_value
        row[x] = 1
        value = row @ w
        if value > lightest_value:
            return
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            if value < lightest_value:
                lightest_value = value
                lightest = row.copy()
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))

    return lightest, lightest_value

def add_constraint(N, c):
    if N is None:
        return c
    return np.vstack((N, c))

def modulus(N, p):
    n = N.shape[-1]

    rho = cvx.Variable(n)

    cons = [rho >= 0, N@rho >= 1]

    obj = cvx.Minimize(cvx.pnorm(1**(1/p)*rho, p)**p)

    prob = cvx.Problem(obj, cons)
    prob.solve(solver=cvx.CLARABEL)

    return obj.value, np.array(rho.value).flatten()

def ssmodulus(pi, p, display=True):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None

    while True:
        m, gP, lv = shortest_path(pi, rho)

        if lv > 1 - tol:
            if display:
                plt.figure(figsize=(6, 6))
                plt.scatter(range(1, len(pi) + 1), pi)
                plt.title(f'Modulus: {round(mod, 3)}')
                for row in m:
                    indices = np.nonzero(row)
                    plt.plot(indices[0] + 1, [pi[i] for i in indices[0]], color='tan')
                for i, j in enumerate(pi):
                    plt.annotate(round(rho[i], 3), (i + 1, j), xycoords='data', xytext=(4, 4), textcoords='offset points')
                plt.xticks(range(0, len(pi) + 2))
                plt.yticks(range(0, len(pi) + 2))
                plt.grid(True)
            return mod, rho, m
        
        N = add_constraint(N, gP)

        mod, rho = modulus(N, p)


def fast_ssmodulus(pi, p, display=False):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None

    while True:
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod
            # return mod, rho

        N = add_constraint(N, gP)

        mod, rho = modulus(N, p)

def faster_ssmodulus(pi, p, display=False):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = generate_N(pi)
    m = None

    # print(len(N))

    # def faster_shortest_path(rho):
    #     lightest_value = math.inf
    #     lightest = []
    #     for row in N:
    #         value = row @ rho
    #         if value < lightest_value:
    #             lightest_value = value
    #             lightest = row
    #     return lightest, lightest_value

    mod, _ = modulus(N, p)

    return mod

    # while True:
    #     # print("running")
    #     gP, lv = faster_shortest_path(rho)

    #     if lv > 1 - tol:
    #         return mod
    #         # return mod, rho

    #     m = add_constraint(m, gP)

    #     mod, rho = modulus(m, p)

# pi = [7, 3, 1, 17, 10, 18, 9, 20, 6, 12, 16, 13, 2, 8, 19, 4, 15, 11, 14, 5]

n = 50
pi = random.sample(range(1, n + 1), n)

#print(ssmodulus(pi, 2, False))
#print(fast_ssmodulus(pi, 2))
#print(faster_ssmodulus(pi, 2))


In [14]:
n = 60
pi = random.sample(range(1, n + 1), n)
print("pi: ", pi)
print("base method: ", end="")
%timeit -r1 -n 1 ssmodulus(pi, 2, display=False)
print("\"improved\" method: ", end="")
%timeit -r1 -n 1 fast_ssmodulus(pi, 2)
print("more improved? method: ", end="")
%timeit -r1 -n 1 faster_ssmodulus(pi, 2)

pi:  [33, 41, 35, 51, 13, 4, 42, 1, 17, 29, 9, 22, 55, 54, 39, 46, 32, 11, 43, 14, 7, 38, 52, 8, 45, 2, 47, 53, 60, 19, 49, 6, 16, 27, 21, 10, 23, 58, 24, 15, 26, 3, 28, 31, 36, 20, 59, 30, 25, 44, 18, 5, 48, 37, 40, 56, 50, 34, 12, 57]
base method: 

AttributeError: module 'cvxpy' has no attribute 'promote'

In [15]:
def basic_matrix(pi, p):
    usage = generate_N(pi)
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None
    while True:
        vals = usage @ rho           # shape (m,)

        # Find the smallest one
        idx_min = np.argmin(vals)
        min_value = vals[idx_min]
        row_min = usage[idx_min]
        print(row_min)

        if min_value > 1 - tol:
            return mod
            # return mod, rho

        N = add_constraint(N, row_min)

        mod, rho = modulus(N, p)

    return mod

n = 5
pi = random.sample(range(1, n + 1), n)
print(pi)
basic_matrix(pi, 2)

[4, 5, 1, 3, 2]
[1. 1. 0. 0. 0.]


AttributeError: module 'cvxpy' has no attribute 'promote'

In [16]:
n = 30
pi = random.sample(range(1, n + 1), n)
print(ssmodulus(pi, 2, False))
print(fast_ssmodulus(pi, 2))
print(faster_ssmodulus(pi, 2))
print(basic_matrix(pi, 2))


AttributeError: module 'cvxpy' has no attribute 'promote'

In [33]:
n = 50
pi = random.sample(range(1, n + 1), n)
print("base method: ", end="")
%timeit -r1 -n 1 ssmodulus(pi, 2, display=False)
print("\"improved\" method: ", end="")
%timeit -r1 -n 1 fast_ssmodulus(pi, 2)
print("more improved? method: ", end="")
%timeit -r1 -n 1 faster_ssmodulus(pi, 2)
print("new ", end="")
%timeit -r1 -n 1 basic_matrix(pi, 2)

base method: 228 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
"improved" method: 147 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
more improved? method: 9.55 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
new 113 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


So far, the fastest way is to do: generate all Misss, and then do cvx

In [17]:

n = 50
pi = random.sample(range(1, n + 1), n)
#print("fast-shortest(recurse)+basic: ", end="")
#%timeit -r1 -n 1 fast_ssmodulus(pi, 2)
#print("usage+all-constraints: ", end="")
#%timeit -r1 -n 1 faster_ssmodulus(pi, 2)
print("usage(recurse)+basic ", end="")
%timeit -r1 -n 1 basic_matrix(pi, 2)

usage(recurse)+basic [1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


AttributeError: module 'cvxpy' has no attribute 'promote'

Need to find the shortest path without lising all MISSes.

Run expectation: 5000 trials for Mod2, Mod1

Hope:log(MOD) =logc+alogn

plot (MOD/n),(MOD/n^(1/2)), plot log(MOD) and log(n), plot MOD and its (MOD)^{-1}

Add expectation of longest MISS

See P(Mincut(pi+j) (i.e fix j at the end) >= mincut(pi)) for a fixed j, 5000 trials each
    See if random permutation can force an index j to be specific value v

For each pi compare MOD1 of it to adding a value to end of pi and MOD of that, if the MOD1 is greater then add 1 to sum if not dont change and take average

If MC(pi) = 2 then MC(pi + j) <= MC(pi) => j = n+1

MC(pi) = 3
When MC(pi + j) < MC(pi)

How often is mincut terminal points?

E(Pareto) is size of terminal points
We showed E(MC) is a subset of E(Pareto) = log(n)

Find prob that mincut is < size of terminal points

E(shortest MISS) <= E(Terminal_(1,0)) = log n
E(longest MISS) = 2sqrt(n)

In [38]:
5000*50*3/3600/64

3.2552083333333335

Compute Expectation of the longest MISS and with / root n

Choose n = 70 and then sketch Min Cut for j=1...j=70, j is x axis, random permutations of length 70, sketch probability that pi+j > pi