In [78]:
# import packages
from fractions import Fraction
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import math
import cvxpy as cvx
import math
import random
# from collections import deque

In [2]:
def all_connections(s):
    """returns all valid connections in MISS

    Args:
        s (list): sequence to generate connections from

    Returns:
        list of tuples: (x1, x2) where (x1, s[x1]) (x2, s[x2]) is a valid connection of up and right paths that are part of a MISS
    """
    # adding auxilary source and sinka
    s = s.copy()
    s.insert(0, 0)
    s.append(len(s))

    connections = []
    for i in range(len(s)):
        for j in range(i, len(s)):
            # using the above rule
            if ((j - i) * (s[j] - s[i])) > 0:
                connections.append((i, j))
    # gets rid of duplicates
    connections = list(set(connections))

    # plt.figure(figsize=(6, 6))
    # plt.scatter(range(0, len(s)), s)

    valid_connections = set()

    for connection in connections:
        if not in_box(connection, s):
            valid_connections.add((connection[0] + 1, connection[1] + 1))
            x1, x2 = connection[0], connection[1]
            # plt.plot([x1, x2], [s[x1], s[x2]], color='tan')

    # plt.xticks(range(0, len(s) + 1))
    # plt.yticks(range(0, len(s) + 1))
    # plt.grid(True)

    connections = sorted(list(valid_connections))

    return connections


def in_box(t, s):
    """returns whether there is another point in the box extending horizontal and vertical lines from both points

    Args:
        t (tuple): connection to be checked
        s (list): main seequence

    Returns:
        bool: whether there exists a point in the box
    """
    i, j = t[0], t[1]
    if any(s[x] < s[j] and s[x] > s[i] for x in range(i + 1, j)):
        return True
    return False

def find_sources(s):
    """finds sources of a sequence (all sources of MISS)

    Args:
        s (list): main sequence

    Returns:
        list: indices of source nodes
    """
    return [i for i, element in enumerate(s) if all(element < x for x in s[:i])]

def recursive_method(s):
    """calls recursive function to find all MISS

    Args:
        s (list): main sequence

    Returns:
        2D numpy array: usage matrix MISS
    """
    m = np.empty((0, len(s)))
    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if len(greater) == 0:
            nonlocal m
            m = np.concatenate((m, [row]), axis=0)
            return
        for element in greater:
            recurse(s, element, row.copy())

    for source in find_sources(s):
        recurse(s, source, np.zeros(len(s))) 
    return m

def MISS_from_connections(c, s_len):
    """uses networkx to find the usage matrix of MISS from a list of possible valid connections

    Args:
        c (list of tuples): connections

    Returns:
        2D numpy array: usage matrix
    """
    g = nx.DiGraph()
    g.add_edges_from(c)
    
    m = np.empty((0, s_len))
        
    sink_nodes = [node for node, out_degree in g.out_degree() if out_degree == 0]
    source_nodes = [node for node, in_degree in g.in_degree() if in_degree == 0]
    for (source, sink) in [(source, sink) for sink in sink_nodes for source in source_nodes]:
        for path in nx.all_simple_paths(g, source=source, target=sink):
            row = np.zeros(s_len)
            for i in path:
                # shifting since auxiliary source and sink should not be in usage matrix
                if i != 1 and i != s_len+2:
                    row[i - 2] = 1
            m = np.concatenate((m, [row]), axis=0)

    return m

def networkx_method(pi):
    return MISS_from_connections(all_connections(pi), len(pi))

def improved_recursive(s):
    m_rows = []

    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))
        
    return np.array(m_rows)

# pi = [7, 3, 1, 17, 10, 18, 9, 20, 6, 12, 16, 13, 2, 8, 19, 4, 15, 11, 14, 5]
# pi = [2, 4, 9, 3, 5, 7, 6, 8, 1]
pi = [2, 1, 4, 5, 3]

print("pi: ", pi)

print("usage matrix using recursive function:")
r = recursive_method(pi)
r = r[np.lexsort(r.T)]
print(r)
print("usage matrix using networkx method:")
n = networkx_method(pi)
n = n[np.lexsort(n.T)]
print(n)
print("usage matrix using improved recursive function:")
i = improved_recursive(pi)
i = i[np.lexsort(i.T)]
print(i)

# plt.figure(figsize=(6, 6))
# plt.scatter(range(1, len(pi) + 1), pi)
# for row in n:
#     indices = np.nonzero(row)
#     plt.plot(indices[0] + 1, [pi[i] for i in indices[0]], color='tan')
# plt.xticks(range(0, len(pi) + 2))
# plt.yticks(range(0, len(pi) + 2))
# plt.grid(True)

print(f"Outputs of all methods are equal: {np.array_equal(n, r) and np.array_equal(n, i)}")

pi2 = [2, 7, 1, 6, 4, 3, 5, 8, 12, 9, 10, 11]
i2 = improved_recursive(pi2)
i2 = i2[np.lexsort(i2.T)]
print(i2)

pi:  [2, 1, 4, 5, 3]
usage matrix using recursive function:
[[1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]
usage matrix using networkx method:
[[1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]
usage matrix using improved recursive function:
[[1. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]
Outputs of all methods are equal: True
[[1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1.]]


In [79]:
from numpy import linalg
import scipy


def find_sources(s):
    return [i for i, element in enumerate(s) if all(element < x for x in s[:i])]

def generate_N(s):
    m_rows = []

    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))
        
    return np.array(m_rows)

def shortest_path(s, w):
    m = np.empty((0, len(s)))
    lightest = np.empty(len(s))
    lightest_value = math.inf
    def recurse(s, x, row):
        row[x] = 1
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if len(greater) == 0:
            nonlocal m, lightest, lightest_value
            m = np.concatenate((m, [row]), axis=0)
            value = np.dot(row, w)
            if value < lightest_value:
                lightest_value = value
                lightest = row
            return
        for element in greater:
            recurse(s, element, row.copy())

    for source in find_sources(s):
        recurse(s, source, np.zeros(len(s))) 

    return m, lightest, lightest_value

# this doens't return N but does give the correct value for modulus
def fast_shortest_path(s, w):
    m_rows = []
    lightest = []
    lightest_value = math.inf

    def recurse(s, x, row):
        nonlocal m_rows, lightest, lightest_value
        row[x] = 1
        value = row @ w
        if value > lightest_value:
            return
        greater = []
        for i in range(x, len(s)):
            if s[i] > s[x] and all(s[j] > s[i] for j in greater):
                greater.append(i)
        if not greater:
            m_rows.append(row.copy())
            if value < lightest_value:
                lightest_value = value
                lightest = row.copy()
            return
        for element in greater:
            recurse(s, element, row)
            row[element] = 0
            
    for i, element in enumerate(s):
        if all(element < x for x in s[:i]):
            recurse(s, i, np.zeros(len(s)))

    return lightest, lightest_value

def add_constraint(N, c):
    if N is None:
        return c
    return np.vstack((N, c))

def modulus(N, p):
    n = N.shape[-1]

    rho = cvx.Variable(n)

    cons = [rho >= 0, N@rho >= 1]

    obj = cvx.Minimize(cvx.pnorm(1**(1/p)*rho, p)**p)

    prob = cvx.Problem(obj, cons)
    prob.solve(solver=cvx.CLARABEL)

    return obj.value, np.array(rho.value).flatten(), np.array(cons[1].dual_value).flatten()

def ssmodulus(pi, p, display=True):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None

    while True:
        m, gP, lv = shortest_path(pi, rho)

        if lv > 1 - tol:
            if display:
                plt.figure(figsize=(6, 6))
                plt.scatter(range(1, len(pi) + 1), pi)
                plt.title(f'Modulus: {round(mod, 3)}')
                for row in m:
                    indices = np.nonzero(row)
                    plt.plot(indices[0] + 1, [pi[i] for i in indices[0]], color='tan')
                for i, j in enumerate(pi):
                    plt.annotate(round(rho[i], 3), (i + 1, j), xycoords='data', xytext=(4, 4), textcoords='offset points')
                plt.xticks(range(0, len(pi) + 2))
                plt.yticks(range(0, len(pi) + 2))
                plt.grid(True)
            return mod, rho, m
        
        N = add_constraint(N, gP)

        mod, rho, _ = modulus(N, p)


def fast_ssmodulus(pi, p, display=False):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None

    while True:
        
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod
            # return mod, rho

        N = add_constraint(N, gP)

        mod, rho, _ = modulus(N, p)

def faster_ssmodulus(pi, p, display=False):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = generate_N(pi)
    m = None

    # print(len(N))

    # def faster_shortest_path(rho):
    #     lightest_value = math.inf
    #     lightest = []
    #     for row in N:
    #         value = row @ rho
    #         if value < lightest_value:
    #             lightest_value = value
    #             lightest = row
    #     return lightest, lightest_value

    mod, _, _ = modulus(N, p)

    return mod

    # while True:
    #     # print("running")
    #     gP, lv = faster_shortest_path(rho)

    #     if lv > 1 - tol:
    #         return mod
    #         # return mod, rho

    #     m = add_constraint(m, gP)

    #     mod, rho = modulus(m, p)




def goldfarb_idnani_slow(pi):
    rho = np.zeros(len(pi), dtype=float)
    mod = 0.0
    tol = 1e-5
    N = None
    t = 0.0
    r = 0
    lambda_0 = np.array([], dtype=float)

    gP, lv = fast_shortest_path(pi, rho)
    gP = np.asarray(gP, dtype=float)

    N = np.atleast_2d(np.asarray(add_constraint(N, gP), dtype=float))
    lambda_0 = np.append(lambda_0, 2.0 / N.sum())

    print(lambda_0)   # shape (1,)
    print(N)          # shape (1, n)

    rho = (1/2)*N.T@lambda_0

   
            
    while True:
        
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod, lambda_0
            # return mod, rho
        
        
        N2 = np.atleast_2d(N)
        r = np.linalg.solve(N2 @ N2.T, N2 @ gP)
        rho_1 = (1/2)* N.T @ lambda_0
        

        lambda_0 = add_constraint(lambda_0, [0])
        print(gP)
        print(r)
        print(N)
        print(np.dot(gP,gP)-np.dot(gP.T,(N.T@r)))
       
        t= (2*(1-np.dot(gP,rho_1))) / (np.dot(gP,gP)-np.dot(gP.T,(N.T@r)))
        print(t)
        N = add_constraint(N, gP)
        print(N)
        print(lambda_0)
        lambda_0 = lambda_0 - t*( np.append(r, -1).reshape(-1, 1))
        print(lambda_0)
        for i in range(len(lambda_0)):
            if lambda_0[i,0] <= 0:
                N=np.delete(N,i,axis=0)

        lambda_0 = lambda_0[lambda_0[:, 0] > 0]
        print(lambda_0)
        rho = (1/2)*N.T@lambda_0
        mod = np.linalg.norm(rho, 2)**2






In [80]:
def goldfarb_idnani_faster(pi):
    rho = np.zeros(len(pi), dtype=float)
    mod = 0
    tol = 1e-5
    N = np.empty((0, len(pi)))
    t = 0.0
    r = 0
    lambda_0 = np.array([], dtype=float)

    gP, lv = fast_shortest_path(pi, rho)
    gP = np.asarray(gP, dtype=float)

    N = np.atleast_2d(np.asarray(add_constraint(N, gP), dtype=float))
    lambda_0 = np.append(lambda_0, 2.0 / N.sum())

    rho = (1/2)*N.T@lambda_0

    while True:
        
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod, lambda_0
            # return mod, rho
        #r = np.linalg.solve(N@N.T, N@gP)
        L = np.linalg.cholesky(N@N.T)
        r = scipy.linalg.cho_solve((L, True), N@gP)
        rho_1 = (1/2)*N.T@lambda_0
        t = (2*(1-np.dot(gP,rho_1))) / (np.dot(gP,gP)-np.dot(gP.T,(N.T@r)))

        removed_row = False

        for i in range(len(lambda_0)):
            if lambda_0[i] <= 0:
                removed_row = True
                #N=np.delete(N,i,axis=0)
                N_1 = N[:i]
                N_2 = N[i+1:]
                N = np.concatenate((N_1, N_2), axis=0)
                first_lambda = lambda_0[:i]
                second_lambda = lambda_0[i+1:]
                L = np.linalg.cholesky(N@N.T)
                lambda_0 = np.concatenate((first_lambda, second_lambda), axis=0)    
                new_N, N = qr_decomp_givens(L)
                #fix still
                #L_11 = np.linalg.cholesky(N_1@N_1.T)
                #L_31 = np.linalg.cholesky(N_2@N_1.T)
                #L_33 = np.linalg.cholesky(N_2@N_2.T)
                #l_32 = 
                N = new_N@new_N.T
                break #only one row can be removed at a time


        if removed_row == False:
            l = np.linalg.inv(L)@N@gP
            #t = math.sqrt(gP.T@gP - l.T@l)
            
            #l_row = l.reshape(1, -1)
            #L = np.block([[L, np.zeros((L.shape[0], 1))], [l_row, np.array([[t]])]])
            #N = L@L.T

            lambda_0 = add_constraint(lambda_0, [0])
            N = add_constraint(N, gP)
                

        #N = add_constraint(N, gP)
        N = np.atleast_2d(N)

        #lambda_0 = add_constraint(lambda_0, [0])
       

        lambda_0 = lambda_0 - t*( np.append(r, -1).reshape(-1, 1))

        

        lambda_0 = lambda_0[lambda_0[:,0] > 0]

        rho = (1/2)*N.T@lambda_0
        mod = np.linalg.norm(rho, 2)**2

In [81]:
# pi = [7, 3, 1, 17, 10, 18, 9, 20, 6, 12, 16, 13, 2, 8, 19, 4, 15, 11, 14, 5]

n = 5
pi = random.sample(range(1, n + 1), n)

print(ssmodulus(pi, 2, False))
print(fast_ssmodulus(pi, 2))
print(faster_ssmodulus(pi, 2))




(1.1666666668046448, array([0.5     , 0.666665, 0.5     , 0.333335, 0.333335]), array([[1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.]]))
1.1666666668046448
1.166666667977002


In [82]:
def givens_rotation(a, b):
    r = np.hypot(a, b)
    if r == 0:
        return 1.0, 0.0
    c = a / r
    s = -b / r
    return c, s

def apply_givens_rotation_left(N, i, j, c, s):
    row_i = N[i, :].copy()
    row_j = N[j, :].copy()
    N[i, :] = c * row_i - s * row_j
    N[j, :] = s * row_i + c * row_j

def qr_decomp_givens(N):
    m, n = N.shape
    Q = np.eye(m)
    R = N.copy()

    for j in range(n):
        for i in range(m - 1, j, -1):
            c, s = givens_rotation(R[i - 1, j], R[i, j])
            apply_givens_rotation_left(R, i - 1, i, c, s)
            apply_givens_rotation_left(Q, i - 1, i, c, s)

    return Q.T, R


# rows 1,2,4,5 and columns 1,2,4,5
def restore_lower_triangular(L):
    """Apply Givens rotations to zero out all L[i, i+1] elements."""
    m, n = L.shape
    for i in range(min(m, n)):
        if abs(L[i, i+1]) > 1e-14:
            a = L[i, i]
            b = L[i, i+1]
            r = np.hypot(a, b)
            c = a / r
            s = b / r
            col_i = L[:, i].copy()
            col_j = L[:, i+1].copy()
            L[:, i]   =  c * col_i + s * col_j
            L[:, i+1] = -s * col_i + c * col_j
    return L

#R = restore_lower_triangular(L1)
#print(np.round(R,3))
#print(np.round(R@R.T,3))


In [83]:
N =np.array([[1, 1, 1, 0, 0],[1,0,0,0,0],[1,0,1,0,1],[1,1,0,0,0]])
L = np.linalg.cholesky(N@N.T)
print(L)
N1 =np.array([[1, 1, 1, 0, 0],[1,0,1,0,1],[1,1,0,0,0]])

L1 = L[np.ix_([0, 2,3], [0,1,2,3])]
print(L1)
print(L1@L1.T)
print(N1@N1.T)
m = np.array([1,1,1])
(m@m.T)**(1/2)

[[ 1.73205081  0.          0.          0.        ]
 [ 0.57735027  0.81649658  0.          0.        ]
 [ 1.15470054  0.40824829  1.22474487  0.        ]
 [ 1.15470054  0.40824829 -0.40824829  0.57735027]]
[[ 1.73205081  0.          0.          0.        ]
 [ 1.15470054  0.40824829  1.22474487  0.        ]
 [ 1.15470054  0.40824829 -0.40824829  0.57735027]]
[[3. 2. 2.]
 [2. 3. 1.]
 [2. 1. 2.]]
[[3 2 2]
 [2 3 1]
 [2 1 2]]


np.float64(1.7320508075688772)

In [84]:
def goldfarb_idnani_faster_2(pi):
    rho = np.zeros(len(pi), dtype=float)
    mod = 0
    tol = 1e-5
    N = np.empty((0, len(pi)))
    t = 0.0
    r = 0
    lambda_0 = np.array([], dtype=float)

    gP, lv = fast_shortest_path(pi, rho)
    gP = np.asarray(gP, dtype=float)

    N = np.atleast_2d(np.asarray(add_constraint(N, gP), dtype=float))
    print(N)
    lambda_0 = np.append(lambda_0, 2.0 / N.sum())

    rho = (1/2)*N.T@lambda_0
    #compute initial L
    L = np.array((np.array(N@N.T))**(1/2)) 

    while True:
        
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod, lambda_0
            # return mod, rho
        #r = np.linalg.solve(N@N.T, N@gP)
        
        r = scipy.linalg.cho_solve((L, True), N@gP)
        rho_1 = (1/2)*N.T@lambda_0
        t = (2*(1-np.dot(gP,rho_1))) / (np.dot(gP,gP)-np.dot(gP.T,(N.T@r)))

        removed_row = False
        check_for_additional_rows = True

        while check_for_additional_rows:
            check_for_additional_rows = False
            for i in range(len(lambda_0)):
                if lambda_0[i] <= 0:
                    removed_row = True
                    check_for_additional_rows = True
                    #N=np.delete(N,i,axis=0)
                    
                    N_1 = N[:i]
                    N_2 = N[i+1:]
                    j = len(N_2)
                    N = np.concatenate((N_1, N_2), axis=0)
                    first_lambda = lambda_0[:i]
                    second_lambda = lambda_0[i+1:]
                    lambda_0 = np.concatenate((first_lambda, second_lambda), axis=0) 
                    #L = np.linalg.cholesky(N@N.T)   
                    new_N, N = qr_decomp_givens(L)
                    L_11 = L[:i, :i]
                    L_31 = L[j:, :i]
                    L_33 = L[j:, j:]
                    l_32 = L[j:, i:i+1]
                    #check zeroes dimensions
                    L = np.block([[L_11, np.zeros((L_11.shape[0], 1)), np.zeros((L_11.shape[0], L_11.shape[1]-L_11.shape[0]))],
                                [L_31, l_32, L_33]])
                    L = restore_lower_triangular(L)
                    break #only one row can be removed at a time


        if removed_row == False:
            l = np.linalg.inv(L)@N@gP
            new_t = math.sqrt(gP.T@gP - l.T@l)
            
            l_row = l.reshape(1, -1)
            L = np.block([[L, np.zeros((L.shape[0], 1))], [l_row, np.array([[new_t]])]])

            lambda_0 = add_constraint(lambda_0, [0])
            N = add_constraint(N, gP)
                

        #N = add_constraint(N, gP)
        N = np.atleast_2d(N)

        #lambda_0 = add_constraint(lambda_0, [0])
       

        lambda_0 = lambda_0 - t*( np.append(r, -1).reshape(-1, 1))

        

        #lambda_0 = lambda_0[lambda_0[:,0] > 0]

        rho = (1/2)*N.T@lambda_0
        mod = np.linalg.norm(rho, 2)**2

In [89]:
import time

start_1 = time.perf_counter()

mod_slow, lambda_slow = goldfarb_idnani_slow(pi)

end_1 = time.perf_counter()

start_2 = time.perf_counter()
mod_fast, lambda_fast = goldfarb_idnani_faster_2(pi)
end_2 = time.perf_counter()

start_3 = time.perf_counter()
print(ssmodulus(pi, 2, False))
end_3 = time.perf_counter()

start_4 = time.perf_counter()
print(fast_ssmodulus(pi, 2))
end_4 = time.perf_counter()

start_5 = time.perf_counter()
print(faster_ssmodulus(pi, 2))
end_5 = time.perf_counter()
print(f"Slow method: {mod_slow}, Fast method: {mod_fast}")
print(f"Time taken for slow goldfarb method: {end_1 - start_1} seconds")
print(f"Time taken for fast goldfarb method: {end_2 - start_2} seconds")
print(f"Time taken for ssmodulus: {end_3 - start_3} seconds")
print(f"Time taken for fast_ssmodulus: {end_4 - start_4} seconds")
print(f"Time taken for faster_ssmodulus: {end_5 - start_5} seconds")


[1.]
[[1. 0. 1. 0. 0.]]
[0. 1. 0. 1. 0.]
[0.]
[[1. 0. 1. 0. 0.]]
2.0
1.0
[[1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]]
[[1.]
 [0.]]
[[1.]
 [1.]]
[[1.]
 [1.]]
[0. 1. 0. 0. 1.]
[0.  0.5]
[[1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]]
1.5
[0.66666667]
[[1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]]
[[1.]
 [1.]
 [0.]]
[[1.        ]
 [0.66666667]
 [0.66666667]]
[[1.        ]
 [0.66666667]
 [0.66666667]]
[[1. 0. 1. 0. 0.]]
(1.1666666668046448, array([0.5     , 0.666665, 0.5     , 0.333335, 0.333335]), array([[1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.]]))
1.1666666668046448
1.166666667977002
Slow method: 1.166666666666667, Fast method: 1.166666666666667
Time taken for slow goldfarb method: 0.004948899964801967 seconds
Time taken for fast goldfarb method: 0.0011177000124007463 seconds
Time taken for ssmodulus: 0.022688900004141033 seconds
Time taken for fast_ssmodulus: 0.012455700081773102 seconds
Time taken for faster_ssmodulus: 0.0039080000

In [ ]:
def goldfarb_idnani(pi):
    rho = np.zeros(len(pi))
    mod = 0
    tol = 1e-5
    N = None
    N_1 = None
    t = 0
    r = 0
    lambda_0 = None

    while True:
        
        gP, lv = fast_shortest_path(pi, rho)

        if lv > 1 - tol:
            return mod, lambda_0
            # return mod, rho

        N = add_constraint(N, gP)
        N = np.atleast_2d(N)

        lambda_0 = add_constraint(lambda_0, [0])

        
        #U = scipy.linalg.cholesky(N@N.T, lower=False)
        add = True
        sub_val = None
        for val in lambda_0:
            if val - t*r < 0:
                #remove
                add = False
                sub_val = val
        
        if add == True:
            
            l = inv_L@(N@gP)
            val = gP.T@gP - l.T@l #gives some floating point noise
            print("gP.T@gP: - l.T@l", gP.T@gP - l.T@l)
            t = math.sqrt(max(0.0, val))
            l_row = l.reshape(1, -1)
            l_col = l.reshape(-1, 1)
            new_left = np.block([[L, np.zeros((L.shape[0], 1))], [l_row, np.array([[t]])]])
            new_right = np.block([[L.T, l_col], [np.zeros((1, L.shape[0])), np.array([[t]])]])
            N_1 = new_left@new_right
            #compute new r here
            b = N@gP
            y = scipy.linalg.solve_triangular(L, b, lower=True)
            r = scipy.linalg.solve_triangular(L.T, y, lower=False)

            t = (2*(1-gP.T*lambda_0)) / (gP.T@gP-gP.T@N_1*r)
        else:
            id = N.index(sub_val)
            first_N = N[:id]
            second_N = N[id+1:]
            first_lambda = lambda_0[:id]
            second_lambda = lambda_0[id+1:]
            concat = np.concatenate((first_N, second_N), axis=0)
            new_lambda = np.concatenate((first_lambda, second_lambda), axis=0)
            L = scipy.linalg.cholesky(concat@concat.T, lower=True)
            U = scipy.linalg.cholesky(concat@concat.T, lower=False)
            new_L, orig_L = qr_decomp_givens(L)
            new_R, orig_R = qr_decomp_givens(U)
            N_1 = new_L@new_R
            lambda_0 = new_lambda
        N = N_1


In [ ]:
n = 50
pi = random.sample(range(1, n + 1), n)
print("pi: ", pi)
print("base method: ", end="")
%timeit -r1 -n 1 ssmodulus(pi, 2, display=False)
print("\"improved\" method: ", end="")
%timeit -r1 -n 1 fast_ssmodulus(pi, 2)
print("more improved? method: ", end="")
%timeit -r1 -n 1 faster_ssmodulus(pi, 2)

pi:  [38, 40, 9, 21, 25, 10, 3, 13, 17, 2, 6, 18, 4, 5, 19, 14, 46, 24, 48, 28, 39, 20, 41, 42, 37, 12, 11, 36, 23, 33, 50, 44, 1, 34, 30, 35, 43, 47, 29, 15, 45, 32, 8, 22, 16, 26, 31, 7, 49, 27]
base method: 538 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
"improved" method: 227 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
more improved? method: 22.3 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
